from enum import StrEnum


class SkillId(StrEnum):
    COUNT_TO_10 = "COUNT_TO_10"
    NUMBER_RECOGNITION_10 = "NUMBER_RECOGNITION_10"
    COMPARE_10 = "COMPARE_10"
    NUMBER_BONDS_5 = "NUMBER_BONDS_5"
    NUMBER_BONDS_10 = "NUMBER_BONDS_10"
    ADD_OBJECTS_10 = "ADD_OBJECTS_10"
    ADD_COUNT_ON_10 = "ADD_COUNT_ON_10"
    ADD_PART_WHOLE_10 = "ADD_PART_WHOLE_10"


class Representation(StrEnum):
    TEN_FRAME = "TEN_FRAME"
    NUMBER_LINE = "NUMBER_LINE"
    PART_PART_WHOLE = "PART_PART_WHOLE"


class Strategy(StrEnum):
    COUNT_ALL = "COUNT_ALL"
    COUNT_ON = "COUNT_ON"
    NUMBER_BONDS = "NUMBER_BONDS"


class Theme(StrEnum):
    DINOSAURS = "DINOSAURS"
    SPACE = "SPACE"


class Classification(StrEnum):
    CORRECT = "CORRECT"
    INCORRECT = "INCORRECT"
    PARTIAL = "PARTIAL"
    NON_ANSWER = "NON_ANSWER"
    UNCERTAIN = "UNCERTAIN"
    INVALID_INPUT = "INVALID_INPUT"


class SessionState(StrEnum):
    START = "START"
    SELECT_SKILL = "SELECT_SKILL"
    CREATE_PROBLEM = "CREATE_PROBLEM"
    VALIDATE_PROBLEM = "VALIDATE_PROBLEM"
    PRESENT_PROBLEM = "PRESENT_PROBLEM"
    WAITING_FOR_ANSWER = "WAITING_FOR_ANSWER"
    CLASSIFY_ANSWER = "CLASSIFY_ANSWER"
    VERIFY_ANSWER = "VERIFY_ANSWER"
    GIVE_HINT = "GIVE_HINT"
    SHOWING_RETEACH = "SHOWING_RETEACH"
    UPDATE_STUDENT = "UPDATE_STUDENT"
    ADVANCE = "ADVANCE"
    PAUSED = "PAUSED"
    RECOVERING = "RECOVERING"
    FALLBACK = "FALLBACK"
    ERROR = "ERROR"
    SESSION_COMPLETE = "SESSION_COMPLETE"
